name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - run: >-
        nix-instantiate
        -I nixos-config=test-userdata.nix
        '<nixpkgs/nixos>'
        -A config.system.build.toplevel
